version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install:
          node-version: "14.15"
      - checkout
      # Checkout and pull
      - run:
          name: Fetch All Files
          command: |
            git fetch --all
            git checkout main
            git pull origin main

      # Install dependencies for the frontend app
      - run:
          name: Install Front-End Dependencies
          command: |
            cd udagram/udagram-frontend  # Ensure you're in the frontend directory
            npm install
            npm install typescript@">=3.4.0 and <3.6.0" --save-dev
      # Install dependencies for the backend API
      - run:
          name: Install API Dependencies
          command: |
            cd udagram/udagram-api  # Ensure you're in the backend directory
            npm install
      # Build the frontend app
      - run:
          name: Front-End Build
          command: |
            cd udagram/udagram-frontend
            npm run build
      # Build the backend API
      - run:
          name: API Build
          command: |
            cd udagram/udagram-api
            ls -la
            npm run build

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "14.15"
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Deploy FrontEnd
          command: |
            echo "Deploying frontend and backend"
            cd udagram/udagram-frontend && npm run deploy
      - run:
          name: Set Up eb-cli Profile
          command: |
            aws configure set aws_access_key_id $AWS_EB_CLI_ACCESS_KEY_ID --profile eb-cli
            aws configure set aws_secret_access_key $AWS_EB_CLI_SECRET_ACCESS_KEY --profile eb-cli
            aws configure set aws_session_token $AWS_EB_CLI_SESSION_TOKEN --profile eb-cli
            aws configure set region us-east-1 --profile eb-cli
      - run:
          name: Deploy Backend
          command: |
            echo "Deploying frontend and backend"
            cd udagram/udagram-api && npm run deploy

workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - main
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
