version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install:
          node-version: '14.15'
      - checkout
      # Install dependencies for the frontend app
      - run:
          name: Install Front-End Dependencies
          command: |
            cd udagram/udagram-frontend  # Ensure you're in the frontend directory
            npm install
            npm install typescript@">=3.4.0 and <3.6.0" --save-dev
      # Install dependencies for the backend API
      - run:
          name: Install API Dependencies
          command: |
            cd udagram/udagram-api  # Ensure you're in the backend directory
            npm install
      # Build the frontend app
      - run:
          name: Front-End Build
          command: |
            cd udagram/udagram-frontend
            npm run build
      # Build the backend API
      - run:
          name: API Build
          command: |
            cd udagram/udagram-api
            npm run build

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '14.15'
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Deploy App
          command: |
            echo "Deploying frontend and backend"
            cd udagram/udagram-frontend && npm run deploy
            cd udagram/udagram-api && npm run deploy

workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - main
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold